### ISSUE TITLE
header

### ISSUE THREAD

**Issue by ghost** [corbane/Libx.Blender#1]
hi

Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?
Because '304' seems to me 3.04 but '340' is 3.40 ?

see: https://fossies.org/linux/blender/doc/blender_file_format/mystery_of_the_blend.html

**Comment by corbane** [comment]
Hello,
Yes, I've noticed this before (e.g. 2.8 files, with a 2.7 tag). If I understood correctly, you are talking about the "minversion" field of the "GLOB" block?
![image](https://user-images.githubusercontent.com/8430545/213931962-6a035af0-3f61-4e1f-beb4-b347c3939cc7.png)
I don't know exactly how to interpret this value, I guess it's the minimum compatible version.
the code that could provide an answer (I guess) is quite complicated and can be found here:
https://developer.blender.org/diffusion/B/browse/master/source/blender/blenloader/intern/

**Comment by ghost** [comment]
No, I'm talking about the version string in the Blender .blend file HEADER (beginne of the file, after "BLEND") :)
There is "304" too for Blender 3.4 and also 3.4.x
So why they add a "0" between?

**Comment by corbane** [comment]
I searched a bit more:

For Blender 2.93.14,
"2" is the major version, "93" the minor version and "14" the patch.
You can read in `BKE_blender_version.h`:
```
/* Blender major and minor version. */
#define BLENDER_VERSION 293
/* Blender patch version for bugfix releases. */
#define BLENDER_VERSION_PATCH 14
```

https://developer.blender.org/diffusion/B/browse/blender-v2.93-release/source/blender/blenkernel/BKE_blender_version.h;v2.93.14$34

Maybe one day there will be version `4.93.5`. This will give:
```
/* Blender major and minor version. */
#define BLENDER_VERSION 493
/* Blender patch version for bugfix releases. */
#define BLENDER_VERSION_PATCH 5
```

here:
https://developer.blender.org/diffusion/B/browse/tag%253A%2520v3.4.1/source/blender/blenkernel/BKE_blender_version.h;ef9ca44dee7fe3e25089dbfc49c69e9eff83ba5a$20

You can read here how major and minor version are interpreted.
https://developer.blender.org/diffusion/B/browse/blender-v3.3-release/build_files/cmake/macros.cmake;v3.3.3$820
The first digit is the major version and the last two digits the minor version.

---

Unfortunately, I couldn't find where `BLENDER_VERSION_PATCH` is saved.
